/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminServiceAccountsRouteImport } from './routes/admin/service-accounts'
import { Route as AdminSystemRolesRouteImport } from './routes/admin/system-roles'
import { Route as AdminTeamsRouteImport } from './routes/admin/teams'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServiceAccountsRoute = AdminServiceAccountsRouteImport.update({
  id: '/service-accounts',
  path: '/service-accounts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSystemRolesRoute = AdminSystemRolesRouteImport.update({
  id: '/system-roles',
  path: '/system-roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => ResetPasswordRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/consent': typeof ConsentRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/service-accounts': typeof AdminServiceAccountsRoute
  '/admin/system-roles': typeof AdminSystemRolesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/service-accounts': typeof AdminServiceAccountsRoute
  '/admin/system-roles': typeof AdminSystemRolesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/consent': typeof ConsentRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/service-accounts': typeof AdminServiceAccountsRoute
  '/admin/system-roles': typeof AdminSystemRolesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/consent'
    | '/forbidden'
    | '/forgot-password'
    | '/reset-password'
    | '/setup'
    | '/sign-in'
    | '/verify-email'
    | '/admin/service-accounts'
    | '/admin/system-roles'
    | '/admin/teams'
    | '/admin/users'
    | '/api/$'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/forbidden'
    | '/forgot-password'
    | '/reset-password'
    | '/setup'
    | '/sign-in'
    | '/verify-email'
    | '/admin/service-accounts'
    | '/admin/system-roles'
    | '/admin/teams'
    | '/admin/users'
    | '/api/$'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/consent'
    | '/forbidden'
    | '/forgot-password'
    | '/reset-password'
    | '/setup'
    | '/sign-in'
    | '/verify-email'
    | '/admin/service-accounts'
    | '/admin/system-roles'
    | '/admin/teams'
    | '/admin/users'
    | '/api/$'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  ForbiddenRoute: typeof ForbiddenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRouteWithChildren
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiSplatRoute: typeof ApiSplatRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/service-accounts': {
      id: '/admin/service-accounts'
      path: '/service-accounts'
      fullPath: '/admin/service-accounts'
      preLoaderRoute: typeof AdminServiceAccountsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/system-roles': {
      id: '/admin/system-roles'
      path: '/system-roles'
      fullPath: '/admin/system-roles'
      preLoaderRoute: typeof AdminSystemRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof ResetPasswordRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminServiceAccountsRoute: typeof AdminServiceAccountsRoute
  AdminSystemRolesRoute: typeof AdminSystemRolesRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminServiceAccountsRoute: AdminServiceAccountsRoute,
  AdminSystemRolesRoute: AdminSystemRolesRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ResetPasswordRouteChildren {
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

const ResetPasswordRouteChildren: ResetPasswordRouteChildren = {
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}

const ResetPasswordRouteWithChildren = ResetPasswordRoute._addFileChildren(
  ResetPasswordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ConsentRoute: ConsentRoute,
  ForbiddenRoute: ForbiddenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRouteWithChildren,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiSplatRoute: ApiSplatRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
